name: Deploy to EC2

on:
  push:
    branches:
      - main   # adjust if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/m1-starter-app"

      - name: Rebuild and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/m1-starter-app/backend

            # Write secrets into .env
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            MONGODB_URI=${{ secrets.PROD_DB_URI }}
            JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.PROD_GOOGLE_CLIENT_ID }}
            EOF

            # Secure .env
            chmod 600 .env

            # Rebuild and run containers
            docker compose --env-file .env down
            docker compose --env-file .env up --build -d
